name: Build iOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install Dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Build app
        run: |
          xcodebuild -workspace LoveTimer.xcworkspace \
                     -scheme LoveTimer \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ${{ github.workspace }}/build/LoveTimer.xcarchive \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/LoveTimer.xcarchive \
                     -exportPath ${{ github.workspace }}/build \
                     -exportOptionsPlist LoveTimer/exportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: LoveTimer-unsigned-ipa
          path: build/*.ipa
